version: 2

sources:
  - name: my_source
    database: DBT_DATABASE
    schema: public
    tables:
      - name: student
        columns:
          - name: student_id
            tests:
              - not_null
          - name: first_name
            tests:
              - not_null
          - name: last_name
            tests:
              - not_null